services:
  app:
    build: .
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      DATABASE_URL: "mysql://symfony:symfony@mariadb:3306/symfony"
    expose:
      - "9000"
    depends_on:
      - mariadb

  nginx:
    image: nginx:1.25
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  mariadb:
    image: mariadb:11.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
